apiVersion: v1
kind: Service
metadata:
  name: urbanmart-backend
  namespace: urbanmart-dev
spec:
  selector:
    app: urbanmart-backend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
